### ISSUE TITLE
Deprecation notice on php 8.2

### ISSUE THREAD

**Issue by deepika-maj** [clue/php-socks-react#114]
On PHP 8.2.13, I have been receiving following deprecation notice:

`PHP Deprecated:  Creation of dynamic property React\Socket\Connection::$bufferSize is deprecated in /###REDACTED###/vendor/clue/socks-react/src/Server.php on line 391`

**Comment by yadaiio** [comment]
Hello @deepika-maj!

Thank you so much for your ticket. I experienced a failing test suite as well in my pull request to run the tests on PHP 8.3 and update the test suite. You can check it out here https://github.com/clue/reactphp-socks/pull/113.

I had a conversation with @SimonFrings and @clue about the errors that were shown. The test suite is currently reporting unhandled promise rejections with promise v3. We agreed to file some additional pull requests to fix the promise v3 unhandled rejections. Once this is merged, we'll update the test suite and then focus on addressing any deprecations.

We'll provide you with an update in here. Thank you for reporting this :+1:

**Comment by cassifyit** [comment]
Hi @deepika-maj,

Thank you once again for your report. The issue has now been resolved with #118. If there are any more issues in the future, please feel free to let us know.

If you are enjoying this improvement and would like to support us in delivering further enhancements, please consider supporting this project, for example by becoming a sponsor ❤️ https://github.com/sponsors/clue
