### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by deepika-maj** [clue/php-socks-react#119]
Does the library already support creating a SOCKS server on IPv6? If it does, a documentation or a mention about it would be a nice addition.

Currently, I am trying to create an IPv6 SOCKS server using the following code, but it is not working:

```
$connector = new Connector([
    'tcp' => [
        'bindto' => "$ipv6Address:0"
    ]
]);

$server = new Server(null, $connector, [$authUser => $authPassword]);
$socket = new SocketServer("$ipv6Address:$socksPort");
$server->listen($socket);
```

The `uri` parameter `$ipv6Address:$socksPort` for `SocketServer` does not look correct for IPv6.

**Comment by prakash** [comment]
It seems like I have to wrap IPv6 address within `[]`:

```
if (filter_var($ipAddress, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6)) {
    $ipAddress = "[$ipAddress]";
}
```

**Comment by deepika-maj** [comment]
It seems like I have to place IPv6 within `[]` to make it work.

**Comment by clue** [comment]
Glad you've got this sorted out already! Quoting ReactPHP's docs in case anybody else stumbles upon this:

> If you want to listen on an IPv6 address, you MUST enclose the host in square brackets:
>
> ```php
> $socket = new React\Socket\SocketServer('[::1]:8080');
> ```
>
> – https://github.com/reactphp/socket#socketserver

Likewise, the same applies to the `bindto` context and any other place where IPv6 addresses are used, so this should be fully supported across the ecosystem.

PRs welcome if you feel there's anything that needs to be added to our docs :+1:
