### ISSUE TITLE
Can't connect to the server remotely

### ISSUE THREAD

**Issue by samuel-allan** [clue/php-socks-react#34]
I'm trying to run the simple server host example [here](https://raw.githubusercontent.com/clue/php-socks-react/master/examples/server.php) with version 0.4, and for some reason while it doesn't directly complain with any errors, the server refuses a connection from outside (remotely) (e.g. with [this](http://www.checker.freeproxy.ru/checker/) proxy checker tool [checker.freeproxy.ru].

I'm not sure whether it is a problem with my setup (in which case I gravely apologize for having asked this question), or whether it is in fact a fault of the script that I (or someone else) has overlooked.
Thanks a lot for your time!

_Misc_

I am using GoDaddy with Deluxe hosting (I have SSH access, e.t.c.)

**Comment by clue** [comment]
>  the server refuses a connection from outside (remotely) (e.g. with this proxy checker tool

Thanks for posting this! There are in fact many networking issues that might interfere with this.
Have you tried the client examples that come with this library? Does this work locally? Can you open a plain TCP/IP connection to the server?

This could be a firewall or NAT issue, a simple misconfiguration or a protocol issue with your checker tool.

I'm currently not aware of any issues in the client or server components of this library and have been using both for years without any known issues whatsoever, so I'm curious what this may boil down to. I'll close this for now, but please feel free to comment and we can look into this and possibly re-open if this is an issue on our end :+1:

**Comment by samuel-allan** [comment]
Hey, thanks a lot for the tips. I do have an issue though (if you can help I'd be really glad, because I'm in real need :( ):
I found out through hard testing (and with the use of your other psocksd utility - which is great by the way) that there are two issues: first for some reason the DNS doesn't get resolved (when psocksd.phar gets run, upon receiving an incoming connection it says: 
```
2016-11-02 20:57:04 #146 connected
2016-11-02 20:57:04 #146 tunnel target: www.google.com:80
2016-11-02 20:57:19 #146 error: Unable to connect to remote target - DNS query for www.google.com failed: too many retries - DNS query for www.google.com timed out
2016-11-02 20:57:19 #146 disconnected (⌚ 15.015s)
```

I tried fixing it with a custom php server script which resolves a DNS, but apparently I either misunderstand how this works, or there is some issue (I'll add code at the bottom if needed).
The second issue is a lot weirder, see, the results I got above were attained from calling the socks server from one psocksd instance to another, when you try calling it externally, however, it doesn't even display any evidence that the external client connected (at least in the first case it says: 'connected'). 

In order to make sure I'm not just hosting locally ('localhost'), I used '*:9051'.

**Comment by samuel-allan** [comment]
ISSUE SOLVED! Was just a server issue. Thanks a lot, if I have time I'll make sure to help you out with anything you need (as this project really helped me).

**Comment by clue** [comment]
Thanks for reporting back and glad your problem has been solved :+1: 

I'm glad to hear, if you like this library, spread the word :-)
