### ISSUE TITLE
Support for proxy chaining

### ISSUE THREAD

**Issue by samuel-allan** [clue/php-socks-react#36]
The SOCKS client implementation of this library (or socks-react) appears to lack support for proxy chaining and/or documentation that explains how to implement this behaviour. The feature in question is client-side support for connecting to a series of SOCKS proxies, one after the other (for example: Client -> First SOCKS Server -> Second SOCKS server -> Internet).

A good example of a library which supports this behaviour is the [WebSocket2 library's example](https://kaimi.io/projects/websock2/docs/html/proxy_chain_8php-example.html).

Anyway, thanks a lot for considering this potential change, and even though I'm not entirely sure this is a feature that is necessary in itself, it would certainly make this library even more functional :D.

**Comment by clue** [comment]
Thanks for your interest and filing this issue :+1: 

This is in fact already supported, I've just added some documentation and an additional example via #42.

I hope this helps :+1:

**Comment by samuel-allan** [comment]
Thanks a ton!
This project has seriously helped me out immensely and I would love to help out with any bugs/features if any such need appears. Regards, huge thanks again.
