### ISSUE TITLE
Friendly Suggestion (Donations)

### ISSUE THREAD

**Issue by samuel-allan** [clue/php-socks-react#72]
Hi!
I am amazed at how far this library has gone!
I was wondering if you were thinking of putting a donation link somewhere (considering the work done I am quite tempted to have used it were it listed on the page)

**Comment by clue** [comment]
@samuel-allan Thank you for your kind words!

I very much appreciate your wish to donate, but at the same time realize that sending and accepting "donations" can be a bit *problematic* for many companies/individuals. As such, I usually don't actively promote this option. Instead, I usually offer companies the option to either "sponsor" a certain feature development and/or hire me for contract work to allow for sustainable open-source development. *If you want this for a commercial project and you want a quote, please check out my profile and send me an email.*

Other than that, I'm always happy to hear back from happy users, so if you like this library, make sure to spread the word :-)
